[package]
name = "didhub-config"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tracing = "0.1"
url = "2"
serde_json = "1"
config = "0.15"