[package]
name = "didhub-error"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = { version = "0.8" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
anyhow = "1"