name: CI

on:
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  build-test-bundle:
    if: >
      (github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') && !startsWith(github.event.head_commit.message, '[release]')) ||
      github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-license
        run: cargo install cargo-license

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: server-rs -> target

      - name: Bundle Release (with SBOM)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          pnpm bundle:release

      - name: Upload Release Bundle
        uses: actions/upload-artifact@v4
        with:
          name: didhub-release-${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
          path: dist/release/didhub-*
 